import { useTranslations } from 'next-intl';
import CustomSelect from '@/components/ui/CustomSelect';

export interface ExportFieldNames {
  entityId: string;
  entityName: string;
  level: string;
}

interface ColumnMappingSelectorProps {
  availableColumns: string[];
  idColumn: string;
  nameColumn: string;
  levelColumn: string;
  onIdColumnChange: (column: string) => void;
  onNameColumnChange: (column: string) => void;
  onLevelColumnChange: (column: string) => void;
  exportFieldNames: ExportFieldNames;
  onExportFieldNamesChange: (fieldNames: ExportFieldNames) => void;
}

export default function ColumnMappingSelector({
  availableColumns,
  idColumn,
  nameColumn,
  levelColumn,
  onIdColumnChange,
  onNameColumnChange,
  onLevelColumnChange,
  exportFieldNames,
  onExportFieldNamesChange,
}: ColumnMappingSelectorProps) {
  const t = useTranslations('entityDefinition');
  const columnOptions = [
    { value: '', label: t('selectPlaceholder') },
    ...availableColumns.map((col) => ({ value: col, label: col })),
  ];

  return (
    <div className="space-y-3">
      <div className="text-xs font-medium" style={{ color: 'var(--text-tertiary)' }}>
        {t('columnMapping')}
      </div>

      <div className="grid grid-cols-3 gap-3">
        {/* ID 컬럼 */}
        <div
          className="p-3 rounded-lg space-y-2"
          style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-primary)' }}
        >
          <label className="text-xs block font-medium" style={{ color: 'var(--text-secondary)' }}>
            {t('idColumn')}
          </label>
          <CustomSelect
            value={idColumn}
            onChange={onIdColumnChange}
            options={columnOptions}
            placeholder={t('selectPlaceholder')}
            size="sm"
            color="#f59e0b"
          />
          <label className="text-xs block" style={{ color: 'var(--text-tertiary)' }}>
            {t('exportName')}
          </label>
          <input
            type="text"
            value={exportFieldNames.entityId}
            onChange={(e) => onExportFieldNamesChange({ ...exportFieldNames, entityId: e.target.value })}
            placeholder={idColumn || 'ID'}
            className="w-full input-compact"
            style={{
              background: 'var(--bg-primary)',
              border: '1px solid var(--border-primary)',
              color: 'var(--text-primary)',
            }}
          />
        </div>

        {/* 이름 컬럼 */}
        <div
          className="p-3 rounded-lg space-y-2"
          style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-primary)' }}
        >
          <label className="text-xs block font-medium" style={{ color: 'var(--text-secondary)' }}>
            {t('nameColumn')}
          </label>
          <CustomSelect
            value={nameColumn}
            onChange={onNameColumnChange}
            options={columnOptions}
            placeholder={t('selectPlaceholder')}
            size="sm"
            color="#f59e0b"
          />
          <label className="text-xs block" style={{ color: 'var(--text-tertiary)' }}>
            {t('exportName')}
          </label>
          <input
            type="text"
            value={exportFieldNames.entityName}
            onChange={(e) => onExportFieldNamesChange({ ...exportFieldNames, entityName: e.target.value })}
            placeholder={nameColumn || t('fallbackName')}
            className="w-full input-compact"
            style={{
              background: 'var(--bg-primary)',
              border: '1px solid var(--border-primary)',
              color: 'var(--text-primary)',
            }}
          />
        </div>

        {/* 레벨 컬럼 */}
        <div
          className="p-3 rounded-lg space-y-2"
          style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-primary)' }}
        >
          <label className="text-xs block font-medium" style={{ color: 'var(--text-secondary)' }}>
            {t('levelColumn')} <span className="font-normal" style={{ color: 'var(--text-tertiary)' }}>{t('optional')}</span>
          </label>
          <CustomSelect
            value={levelColumn}
            onChange={onLevelColumnChange}
            options={columnOptions}
            placeholder={t('autoGenerated')}
            size="sm"
            color="#f59e0b"
          />
          <label className="text-xs block" style={{ color: 'var(--text-tertiary)' }}>
            {t('exportName')}
          </label>
          <input
            type="text"
            value={exportFieldNames.level}
            onChange={(e) => onExportFieldNamesChange({ ...exportFieldNames, level: e.target.value })}
            placeholder={levelColumn || t('fallbackLevel')}
            className="w-full input-compact"
            style={{
              background: 'var(--bg-primary)',
              border: '1px solid var(--border-primary)',
              color: 'var(--text-primary)',
            }}
          />
        </div>
      </div>

      <p className="text-sm" style={{ color: 'var(--text-tertiary)' }}>
        {t('columnMappingHelp')}
      </p>
    </div>
  );
}
