// SPDX-License-Identifier: AGPL-3.0-or-later
package com.balruno.project.internal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.generator.EventType;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

/**
 * JPA shape of a project. The id is generated by the PG column DEFAULT
 * {@code uuidv7()} and Hibernate reads it back through the RETURNING
 * clause (Hibernate's {@code @UuidGenerator(style=TIME)} would emit v1
 * rather than v7 despite the name).
 */
@Entity
@Table(name = "projects")
class ProjectEntity {

    @Id
    @Generated(event = EventType.INSERT)
    @Column(name = "id", nullable = false, updatable = false, insertable = false)
    private UUID id;

    @Column(name = "workspace_id", nullable = false, updatable = false)
    private UUID workspaceId;

    @Column(name = "slug", nullable = false, length = 30)
    private String slug;

    @Column(name = "name", nullable = false, length = 120)
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "created_by", nullable = false, updatable = false)
    private UUID createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    // ── sync phase columns (V8) ───────────────────────────────────────
    // 3 영역 (시트 셀 / 시트 트리 / 문서 트리) 의 JSONB blob + version.
    // ADR 0008 v2.0 그대로. JSON 직렬화는 String 으로 두고 jsonb_set
    // patch 는 native query 로 처리 (sync 모듈 owner). JPA 는 schema
    // validate 만 — read/write 는 sync 모듈의 native SQL.

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "data", nullable = false, columnDefinition = "jsonb")
    private String data = "{}";

    @Column(name = "data_version", nullable = false)
    private long dataVersion = 1L;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "sheet_tree", nullable = false, columnDefinition = "jsonb")
    private String sheetTree = "[]";

    @Column(name = "sheet_tree_version", nullable = false)
    private long sheetTreeVersion = 1L;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "doc_tree", nullable = false, columnDefinition = "jsonb")
    private String docTree = "[]";

    @Column(name = "doc_tree_version", nullable = false)
    private long docTreeVersion = 1L;

    protected ProjectEntity() {}

    ProjectEntity(UUID workspaceId, String slug, String name, String description, UUID createdBy) {
        this.workspaceId = workspaceId;
        this.slug = slug;
        this.name = name;
        this.description = description;
        this.createdBy = createdBy;
    }

    @PrePersist
    void onCreate() {
        var now = OffsetDateTime.now(ZoneOffset.UTC);
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = OffsetDateTime.now(ZoneOffset.UTC);
    }

    public UUID getId() { return id; }
    public UUID getWorkspaceId() { return workspaceId; }
    public String getSlug() { return slug; }
    public String getName() { return name; }
    public String getDescription() { return description; }
    public UUID getCreatedBy() { return createdBy; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }
    public OffsetDateTime getDeletedAt() { return deletedAt; }
    public boolean isDeleted() { return deletedAt != null; }

    // sync state — read-only via JPA. The sync module mutates via
    // native jsonb_set queries inside @Transactional service code, not
    // by setting these fields. Read-only getters let other modules
    // hydrate the initial sync.full payload without coupling to schema.
    public String getData()             { return data; }
    public long   getDataVersion()      { return dataVersion; }
    public String getSheetTree()        { return sheetTree; }
    public long   getSheetTreeVersion() { return sheetTreeVersion; }
    public String getDocTree()          { return docTree; }
    public long   getDocTreeVersion()   { return docTreeVersion; }

    void rename(String newName) { this.name = newName; }
    void changeSlug(String newSlug) { this.slug = newSlug; }
    void changeDescription(String newDescription) { this.description = newDescription; }
    void softDelete() {
        if (this.deletedAt == null) {
            this.deletedAt = OffsetDateTime.now(ZoneOffset.UTC);
        }
    }
}
