/**
 * Game engine export — render a sheet as a C# struct array (ADR 0033).
 *
 * The game-balance feedback loop in Unity / Godot / engines:
 *   designer edits Balruno → exports → drops file in /Assets → game
 *   reloads with new values. CSV works but a typed C# struct array
 *   means *no parse-by-hand* on the engine side.
 *
 * Sheet's `exportClassName` field (already on the schema) drives the
 * struct name. Each column becomes a field; the value's first non-null
 * cell decides the type (int / float / string / bool).
 */

import type { Sheet, Column, Row, CellValue } from '@/types';

export function sheetToCSharpStruct(sheet: Sheet, options?: { namespace?: string }): string {
  const className = (sheet.exportClassName ?? sanitiseId(sheet.name) ?? 'BalrunoEntry') || 'BalrunoEntry';
  const ns = options?.namespace ?? 'GameData';

  const fieldDefs = sheet.columns.map((c) => ({
    column: c,
    name: sanitiseId(c.name) || sanitiseId(c.id) || 'field',
    type: inferCSharpType(c, sheet.rows),
  }));

  const lines: string[] = [];
  lines.push('// Auto-generated by Balruno. Do not edit by hand.');
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('using System;');
  lines.push('');
  lines.push(`namespace ${ns}`);
  lines.push('{');
  lines.push(`    [Serializable]`);
  lines.push(`    public struct ${className}`);
  lines.push('    {');
  for (const f of fieldDefs) {
    lines.push(`        public ${f.type} ${f.name};`);
  }
  lines.push('    }');
  lines.push('');
  lines.push(`    public static class ${className}Data`);
  lines.push('    {');
  lines.push(`        public static readonly ${className}[] All = new ${className}[]`);
  lines.push('        {');
  for (const row of sheet.rows) {
    const args = fieldDefs.map((f) => formatCSharpValue(f.type, row.cells[f.column.id]));
    lines.push(`            new ${className} { ${fieldDefs.map((f, i) => `${f.name} = ${args[i]}`).join(', ')} },`);
  }
  lines.push('        };');
  lines.push('    }');
  lines.push('}');
  return lines.join('\n');
}

export function downloadCSharpStruct(sheet: Sheet): void {
  const text = sheetToCSharpStruct(sheet);
  const blob = new Blob([text], { type: 'text/x-csharp' });
  const url = URL.createObjectURL(blob);
  const className = (sheet.exportClassName ?? sanitiseId(sheet.name) ?? 'BalrunoEntry');
  const a = document.createElement('a');
  a.href = url;
  a.download = `${className}.cs`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function inferCSharpType(column: Column, rows: Row[]): string {
  // Column type hint first, then sample cell values. Numeric defaults
  // to float when any decimal value is present, otherwise int.
  switch (column.type) {
    case 'checkbox':
      return 'bool';
    case 'currency':
    case 'rating':
      return 'float';
    case 'date':
      return 'string';
    default:
      break;
  }
  let sawNumber = false;
  let sawDecimal = false;
  for (const row of rows) {
    const v = row.cells[column.id];
    if (v === null || v === undefined || v === '') continue;
    if (typeof v === 'number') {
      sawNumber = true;
      if (!Number.isInteger(v)) sawDecimal = true;
    } else if (typeof v === 'string' && /^-?\d+(\.\d+)?$/.test(v)) {
      sawNumber = true;
      if (v.includes('.')) sawDecimal = true;
    } else {
      return 'string';
    }
  }
  if (sawNumber) return sawDecimal ? 'float' : 'int';
  return 'string';
}

function formatCSharpValue(type: string, v: CellValue | undefined): string {
  if (v === null || v === undefined || v === '') {
    return type === 'string' ? '""' : type === 'bool' ? 'false' : '0';
  }
  if (type === 'bool') {
    const truthy = v === 'true' || v === 1 || v === '1';
    return truthy ? 'true' : 'false';
  }
  if (type === 'int' || type === 'float') {
    if (typeof v === 'number') return String(v);
    return String(v);
  }
  // string
  const s = String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${s}"`;
}

function sanitiseId(s: string | null | undefined): string {
  if (!s) return '';
  // C# identifier: letter or underscore start, then word chars.
  let cleaned = s
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (cleaned.length === 0) return '';
  if (/^[0-9]/.test(cleaned)) cleaned = '_' + cleaned;
  return cleaned;
}
